name: Conditional Run

on:
    push:

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Determine Changes
            uses: dorny/paths-filter@v2
            id: filter
            with:
              # Path to file where filters are defined
              filters: |
                    backend:
                    - 'src/folder1/**'
                    frontend:
                    - 'src/folder2/**'
                    weekend:
                        - 'src/folder3/**'

            # run only if 'backend' files were changed
          - name: backend tests
            if: steps.filter.outputs.backend == 'true'
            run: echo "backend tests"

            # run only if 'frontend' files were changed
          - name: frontend tests
            if: steps.filter.outputs.frontend == 'true'
            run: echo "frontend tests"

            # run if 'backend' or 'frontend' files were changed
          - name: e2e tests
            if: steps.filter.outputs.backend == 'true' || steps.filter.outputs.frontend == 'true' || steps.filter.outputs.weekend == 'true'
            run: echo "e2e tests"