name: Dispatch Remotely

on:
  push:

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run 41669286 -R nushio/github-workflow-test-1